### ISSUE TITLE
🌟 [EPIC] 1. Docker is running

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1]
## 🌟 EPIC

- [x] Docker is running
- [x] Services work together
- [x] Tests are running on Github (e.g. Docker builds)
