### ISSUE TITLE
🚀 [Feature] Build Admin Interface User Management

### ISSUE THREAD

**Issue by Elweyn** [gradido/gradido#1059]
## 🚀 Feature
As supporter we need to find User, edit User Informations, send User activation email or send reset email.
Furthermore it would be great to see the coin creation of a User in his profil.

## ToDos:
- [x] Create User Management Page
- [x] Create User Search Component
- [x] Update User Component
- [x] Coin Created Component for User

**Comment by ogerly** [comment]
alles erledigt
