### ISSUE TITLE
🚀 [Feature] Build Admin Interface Coin Creation Management

### ISSUE THREAD

**Issue by Elweyn** [gradido/gradido#1060]
## 🚀 Feature
As Supporter we need to create coins for multiple users, for this we have a page with every user or a filtered list.
In this list we need: 
- Select every User that gets a coin creation, 
- A user that has >= 1000 coins creation for the selected month needs to be fade out / not selectable
- Select one date for all creations, 
- Enter a message for all creations,
- Enter one amount for all creations,
- Each User gets a own message
- Each User gets a own amount
- Edit and Delete a coin creation

## ToDos:
- [ ] Create Coin Creation Management Page
- [ ] Use User Search Component / slots for specific user coin creation fields (Select, Message, Amount) \
- [ ] Coin Creation Form Component / Date, Message, Amount for all creations \
- [ ] Create a Coin Creation Transaction Page
- [ ] Coin Creation Transaction Component / Edit & Delete \

**Comment by ogerly** [comment]
work an this https://github.com/gradido/gradido/issues/1124
