### ISSUE TITLE
🚀 [Feature] Build Admin Interface Coin Creation Transaction List

### ISSUE THREAD

**Issue by Elweyn** [gradido/gradido#1061]
## 🚀 Feature
As supporter we need to have a list of coin creations with their informations, so that we can edit or delete some.

## ToDo
- [x] Create Transaction List Page
- [x] Create Transaction Search Component
- [x] Edit and Delete functionality

**Comment by ulfgebhardt** [comment]
I think we should not allow to edit or delete transactions. This violates perceived banking "standards".

**Comment by ogerly** [comment]
> I think we should not allow to edit or delete transactions. This violates perceived banking "standards".
du you mean actual transaction or gdd creation  ?

**Comment by ulfgebhardt** [comment]
Once a gdd transaction is visible on an account it should never be taken back. There can be additional transactions to correct a faulty state. But once booked things should never be changed. This does not mean we can create Transactions in two steps - create the transaction and then confirm it to make it permanent and irreversible.

**Comment by Elweyn** [comment]
I think that this is done. What do you think? @ogerly @ulfgebhardt?
We get a list of not confirmed pending creations.

Or was this to get a list of all confirmed creations?

**Comment by ogerly** [comment]
this task is completed. i am completing this task.
