### ISSUE TITLE
🐛 [Bug] EloPage Registration no publisher for user 

### ISSUE THREAD

**Issue by Elweyn** [gradido/gradido#1097]
## 🐛 Bugreport
User has registrated without pid and is now registrated in EloPage without publisher. 
The expected result should be that he has a default publisher.

## TODOs:
- [x] Check if login_users publisherId = null => gives back url with default pid.
- [x] If it is the case we need to check if EloPage store the sended pid in a Cookie
- [x] If User withdraw the pid argument from the EloPage link => Stores the User without publisher

**Comment by Elweyn** [comment]
Hi @BerndHueckstaedt,
like we discussed yesterday in the meeting got the code with the tag 1.5.1. 
@ulfgebhardt & @einhornimmond: Is this the right tag? Or is it something like: b1.5.1.421?

With the code of tag 1.5.1: 
- Call http://localhost:3000/vue/
- Click on create new user
- Enter values in form: Max Muster, example14@mumble.com, ... => Create
- Login
- Link to Members Area: https://elopage.com/s/gradido/basic-de/payment?locale=de&prid=111&pid=2896&firstName=Max&lastName=Muster&email=example14@mumble.com

This seems correct in my eyes!

- Now do not click "Kostenlos registrieren" 
- Open new tab with the following URL:
https://elopage.com/s/gradido/basic-de/payment?locale=de&prid=111&firstName=Max&lastName=Muster&email=example14@mumble.com
- Click auf "Kostenlos registrieren"

## TODO:
- [ ] Check EloPage User (Max, Muster, example14@mumble.com) publisher?
- [ ] If the user has no publisher => EloPage does not store the pid in a cookie.

**Comment by Elweyn** [comment]
The User get's the right link even when their is no or an empty pid given!
The only case where EloPage does not set a publisher is when a user get's their and takes out the pid in the url!

This is what we expect so we can close

**Comment by einhornimmond** [comment]
Yes 1.5.1 or you go directly on my branch with the hotfixes:
https://github.com/gradido/gradido/tree/login_hotfixes_1.5.1_reopen
It was already merged with master, but originally I have updated the code from 1.5.1.
