### ISSUE TITLE
🚀 [Feature] Profile & Profile Settings

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#126]
## :rocket: Feature

Implement Profile & Profile Settings

Implement all Features available in the backend. Like:
- name
- lastname
- language
- password 
- email
- picture (optional)

User needs to see and edit his preferences/settings of his profile

- [x] Profile Page with data from above
- [x] Possibility to edit the profile (on the same page)
- [x] Implement the existing API to change user data
- [x] ~~Remove "Beschreibung" field from user data in the backend or find a way to display it to other users or make it useful for others. Is this important for a banking software?~~
- [x] ~~language switch (related #209 )~~
- [x] Change password #409
- [x] ,~~(optional) Change EMail #249~~
- [x] ~~(optional) Remove Language Menu and only offer it in the profile. Requires #353 ~~
- [x] ~~(optional) Picture Upload.~~

If you implement Image upload, please hide the feature from the users eye since we need to incorporate the image in different parts (transaction list, user menu, ....) unless you want to fully implement all of it (related: #181 )

Feel free to split this up further, merge parts etc. For the release this should be completely done.

Old Frontend:

![image](https://user-images.githubusercontent.com/1238238/118051318-10445980-b381-11eb-9618-e3aa5370fe43.png)
![image](https://user-images.githubusercontent.com/1238238/118051336-1c301b80-b381-11eb-9c52-4b0fefdfcbca.png)
