### ISSUE TITLE
🔧 [Refactor] `currentpage` Should Start With `0` Instead of `1`

### ISSUE THREAD

**Issue by Tirokk** [gradido/gradido#1928]
## 🔧 Refactor ticket

`currentpage` should start with `0` instead of `1`.

### Todo

- [ ] `searchUsers`
  - [ ] should `currentPage` start with `1` instead of `0`
  - [ ] `SearchUsersArgs`:
    - [ ] remove `?` from `currentPage` and `pageSize`
      - [ ] make them unullable
    - [ ] have a pagination InputType?
- [ ] `listTransactionLinksAdmin`
  - [ ] should `currentPage` start with `1` instead of `0`? i don't think so! make new issue?
  - [ ] `filters`: shall be nullable?
  - [ ] have a pagination InputType?

**Comment by Mogge** [comment]
This is no good idea. Look at this (`frontend/src/components/Transactions/TransactionLinkSummary.vue`):
```
      if (this.currentPage === 0) {
        this.transactionLinks = []
        this.currentPage = 1
      }
```
We have a working mechanism. Please do not change this. There is no need to do this.

**Comment by Tirokk** [comment]
I wouldn't put specialities of bootstrap into the backend, but I accept if you @Mogge and @ogerly have a different opinion.
Okidoki 😉
