### ISSUE TITLE
🌟 [EPIC] Wallet new style template

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#2002]
## 🌟 EPIC
@Hardy-Hart-am-Start has worked out a new template. The following list divides the large task into subsections and subtasks. 

The pure order of the spiral is the order on the view of the pad and the mobile version.

The most important thing is the basic template which neatly represents all positions and the various forms of presentation. this can / must function neatly without content in the beginning. 

The next step would be basic header and basic menu, 
then the already existing content can be adapted to the new design. 

then the work with the contribution can begin. 

the right-hand box is optional, as there is hardly any feature ready for it... 
except for last transactions and links. 

a special feature is the header in the content area. 

 
 
![Main-Page-Epic-Issues-desktop](https://user-images.githubusercontent.com/1324583/175907450-c107cf7a-fad2-4fd8-a3d8-c2abda559617.png)

 
# first Step

- [x] https://github.com/gradido/gradido/issues/2003 Create a template framework that behaves properly for D-P-M. Without content. Please pay attention to the background image. 

# second step

### 1 Header Bereich
- [ ] https://github.com/gradido/gradido/issues/2005 Create the header, adapt the behaviour to D-P-M *.. 

### 2 Rechter Bereich 
- [ ] https://github.com/gradido/gradido/issues/2006 Create the content area for the right-hand side, making sure that there will be different box systems. adapt the behaviour to D-P-M *. 

### 3 linker Bereich
- [ ] https://github.com/gradido/gradido/issues/2004 Create the menu, adjust the behaviour to D-P-M *. 

### 4 Content Header Box
- [ ] https://github.com/gradido/gradido/issues/2007 Create header for the content area for the start page, adjust the behaviour to D-P-M *.

### 5 Content Bereich
- [ ] https://github.com/gradido/gradido/issues/2008 Create the content area for the start page, adjust the behaviour to D-P-M *. 

* D-P-M = Desktop, Pad, Mobil

**Comment by ogerly** [comment]
done
