### ISSUE TITLE
🚀 [Feature] Change text of EMail templates

### ISSUE THREAD

**Issue by Elweyn** [gradido/gradido#2226]
## 🚀 Feature

- Bitte den Text der Rückfrage rausnehmen, sonst antworten die alle auf die Mail, Rückfrage neu mit einigen Korrekturen:

```
Hallo Bernd Email-Test,

du hast soeben zu deinem eingereichten Gemeinwohl-Beitrag "Kinder gehütet" eine Rückfrage von Bernd von Gradido erhalten.

Bitte beantworte die Rückfrage in deinem Gradido-Konto im Menü "Gemeinschaft" im Tab "Meine Beiträge zum Gemeinwohl"!

Link zu Deinem Konto: https://stage2.gradido.net/overview

Bitte antworte nicht auf diese E-Mail!

Mit freundlichen Grüßen,
dein Gradido-Team
```
- Gradido Transaktion erhalten
```
Hallo Bernd Email-Test

du hast soeben 20,00 GDD von Bernd von Gradido (joytopia@gmail.com) erhalten.

Details zur Transaktion findest du in deinem Gradido-Konto: https://stage2.gradido.net/overview

Bitte antworte nicht auf diese E-Mail!

Mit freundlichen Grüßen,
dein Gradido-Team 
```
- Dein Gemeinwohl-Beitrag wurde bestätigt
```
Hallo Bernd Email-Test,

Dein eingereichter Gemeinwohl-Beitrag "Kinder gehütet" wurde soeben von Bernd von Gradido bestätigt.

Betrag: 100,00 GDD

Bitte antworte nicht auf diese E-Mail!

Mit freundlichen Grüßen,
dein Gradido-Team


Link zu deinem Konto: https://stage2.gradido.net/overview 
```
- Gradido-Link wurde eingelöst
```
Hallo Bernd von Gradido

Bernd Email-Test (bernd.email-test@gradido.net) hat soeben deinen Link eingelöst.

Betrag: 20,00 GDD,
Text: Super, danke, große Klasse!

Details zur Transaktion findest du in deinem Gradido-Konto: https://stage2.gradido.net/overview

Bitte antworte nicht auf diese E-Mail!

Mit freundlichen Grüßen,
dein Gradido-Team
```
## TODOs
- [ ] Remove question text from e-mail & change text to new template
- [ ] Transaction receved: Change text to new template
- [ ] Contribution accepted: Change text to new template
- [ ] Link has been delivered: Change text to new template
