### ISSUE TITLE
🌟 [EPIC] New Design

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#2290]
This is where all the work and branches are pulled together. 

## 🌟 EPIC
The following issues are open 

- [ ] Framework  2003 basic framework template #2026 
- [ ] Menu 2004 basic menu #2033 
- [ ] Header 2005 basic header #2028 
- [ ] Content Area #2304
