### ISSUE TITLE
🔧 [Refactor] Do not delete contributions, but mark them as rejected

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2332]
## 🔧 Refactor ticket

Do not delete contributions, but mark them as rejected.

Currently contributions are deleted when rejecting them. This is incorrect. Make sure that we properly mark them as rejected and have deleted as another state.

Check the database for consistency regarding those states - we need to save the corresponding information exactly one time, not more not less.

## Use cases
- The admin should be able to delete inappropriate content(e.g. insult). Hence we need the delete in the admin.
- The user must be able to delete his contributions when he wants to mark it as invalid (e.g. double claim). Hence the user must be able to delete his unconfirmed contributions.
- The admin user must be able to reject a contribution(e.g. petted the cat). Those must be shown to the user and the community.
- The admin must be able to reopen a rejected or restore a deleted contribution(e.g. rejected was discussed via email and new solution was reached)
- (opt) The user must be able to restore contributions he has deleted himself

## Visibility
- wallet > my contributions > everything
- wallet > community > accepted, rejected, pending
- admin > user search > creation list > everything
- admin > unconfirmed contributions > only pending

## TODO
- [X] Create a method to rejectContribution (for admins)
- [X] Find contribution
- [x] Update contribution (state = rejected, rejectedAt = now, rejectedBy = adminUser.id, ...)
- [x] Save updatedContribution
- [x] Send EMail to user
- [x] wallet > my contributions > everything
- [x] wallet > community > accepted, rejected, pending
- [x] admin > user search > creation list > everything
- [x] admin > unconfirmed contributions > only pending

**Comment by Elweyn** [comment]
Hi @ulfgebhardt @clauspeterhuebner 

Jetzt kommen mir paar Fragen auf:
- Soll der Soft delete (Löschen) entfernt werden oder nicht?
- Was passiert mit "Abgelehnt Contributions"? Anzeige unter Gemeinschaft > Meine Beiträge zum Gemeinwohl? Anzeige unter Gemeinschaft > Gemeinschaft?
- Was passiert mit "Gelöschte Contributions"? Anzeige unter Gemeinschaft > Meine Beiträge zum Gemeinwohl? Anzeige unter Gemeinschaft > Gemeinschaft?
- Was passiert mit Abgelehnte oder Gelöschte Contributions? Möglicher Statuswechsel? Wenn Ja wo (neue Seite im Admin interface)?

**Comment by Elweyn** [comment]
- User kann delete contribution, Admin can delete and deny.
- Denied Contribution should appear in the public list (Frontend) / Admin should filter them out
- User should see denied and deleted contribution in his own list
- Admin interface > User search details > Contribution list: Should show every contribution (PENDING, DELETED, CONFIRM, DENIED, ...)

**Comment by Elweyn** [comment]
TODO:
- [X] Create a method to rejectContribution (for admins)
- [X] Find contribution
- [ ] Update contribution (state = rejected, rejectedAt = now, rejectedBy = adminUser.id, ...)
- [ ] Save updatedContribution
- [ ] Send EMail to user

**Comment by ulfgebhardt** [comment]
@Elweyn 

Use cases:
- The admin should be able to delete inappropriate content(e.g. insult). Hence we need the delete in the admin.
- The user must be able to delete his contributions when he wants to mark it as invalid (e.g. double claim). Hence the user must be able to delete his unconfirmed contributions.
- The admin user must be able to reject a contribution(e.g. petted the cat). Those must be shown to the user and the community.
- The admin must be able to reopen a rejected or restore a deleted contribution(e.g. rejected was discussed via email and new solution was reached)
- (opt) The user must be able to restore contributions he has deleted himself

**Comment by ulfgebhardt** [comment]
@Elweyn 

Visibility:
- wallet > my contributions > everything
- wallet > community > accepted, rejected, pending
- admin > user search > creation list > everything
- admin > unconfirmed contributions > only pending
