### ISSUE TITLE
🚀 [Feature] [Admin] Contributions List

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2594]
## 🚀 Feature

[Admin] Contributions List

Currently you can only access
- contributions per user
- open contributions

### TODOs
- [ ] Make the open contributions page always visible in the menu.
- [ ] The page must contain two tabs (open contributions, all contributions)
- [ ] if the open contributions contains items a red badge with the number of open contributions must be shown in the menu and on the tab, aswell as on the overview page.
- [ ] the `all contributions` must be ordered by the contribution with the last action on it (`updated_at`?) - e.g. confirmed, denied, deleted, ...
- [ ] additional tabs for filters are thinkable: `deleted`, `denied`, `confirmed`. All of those must be queried by the same graphQL query taking a list of filters(e.g. no filter = all, [' denied', 'confirmed'] for those two)
