### ISSUE TITLE
Refactor: backend test add seeding for contributions 

### ISSUE THREAD

**Issue by Elweyn** [gradido/gradido#2653]
# Refactor
In the backend ContributionResolver we need some better tests.
Now we mock some answers and check that there is no contribution with wrong state, and now we need to add some contributions to better test it. 

# TODO 
- [ ] Add IN_PROGRESS contributions in the database
- [ ] Add DENIED contributions in the database
- [ ] Add DELETED contributions in the database

_Originally posted by @Elweyn in https://github.com/gradido/gradido/issues/2619#issuecomment-1413323752_
