### ISSUE TITLE
🚀 [Feature] Backend – Emails – Adjust Namings of Menus to New Frontend Design

### ISSUE THREAD

**Issue by Tirokk** [gradido/gradido#2752]
## 🚀 Feature

Backend – E-Mails – Adjust Namings of Menus to New Frontend Design.

### Todo

- [x] change if design is already implemented or if necessary make issue for:
  - [x] reminder that the email texts have to be adjusted if the menu namings are changing with the new design for:
    - [x] contribution emails `addedContributionMessage`, `contributionRejected`:
      - [x] contribution menu will be renamed
        - search for:
          - de: `„Gemeinschaft“` and `„Meine Beiträge zum Gemeinwohl“`
          - en: `“Community”` and `“My contributions to the common good”`
