### ISSUE TITLE
🚀 [RM-Epic] KlickTipp-Tags

### ISSUE THREAD

**Issue by clauspeterhuebner** [gradido/gradido#2857]
## 🚀 Feature: Describe in this issue the business requirements and processes

Gradido-Konto zu Klick-Tipp API
-------------------------------------
The named fields needs to be called with there api parameter:
<table>
  <tr>
    <th> Step 1 </th>
    <th> Step 2 </th>
    <th> Step 3 </th>
  </tr>
  <tr>
    <td>
      <table>
        <tr><th>Parameter für API</th><th>Field name</th></tr>
        <tr>
          <td>field186061</td><td>GDD date of registration</td>
        </tr>
        <tr>
          <td>field185675</td><td>GDD last created</td>
        </tr>
        <tr>
          <td>field185676</td><td>GDD last invited</td>
        </tr>
        <tr>
          <td>field186060</td><td>GDD last login</td>
        </tr>
        <tr>
          <td>field185674</td><td>GDD last received</td>
        </tr>
        <tr>
          <td>field185673</td><td>GDD last sent</td>
        </tr>
      </table>
    </td>
    <td>
      <table>
        <tr><th>Parameter für API</th><th>Field name</th></tr>
        <tr>
          <td>field185790</td><td>GDD created count 30 days</td>
        </tr>
        <tr>
          <td>field185423</td><td>GDD invited count 30 days</td>
        </tr>
        <tr>
          <td>field185789</td><td>GDD received count 30 days</td>
        </tr>
        <tr>
          <td>field185787</td><td>GDD sent count 30 days</td>
        </tr>
        <tr>
          <td>field185424</td><td>GDD invited count total</td>
        </tr>
      </table>
    </td>
    <td>
      <table>
        <tr><th>Parameter für API</th><th>Field name</th></tr>
        <tr>
          <td>field186150</td><td>GDD Home-Community URL</td>
        </tr>
      </table>
    </td>
  </tr>
</table>

-------------------------------------

*Felder angelegt:*
1. Last: Wann wurde die Aktion das letzte Mal ausgeführt?
- [x] #2877
  - [x] 'GDD last invited': Datum & Zeit:
       entspricht EVENT_TRANSACTION_SEND_REDEEM
  - [x] Datum & Zeit: 'GDD last sent'        
       entspricht EVENT_TRANSACTION_SEND
  - [x] Datum & Zeit: 'GDD last received'  
       entspricht EVENT_TRANSACTION_RECEIVE
  - [x] Datum & Zeit: 'GDD last created'    
       entspricht EVENT_ADMIN_CONTRIBUTION_CONFIRM oder EVENT_CONTRIBUTION_CREATE
  - [x] Datum & Zeit: GDD last login
  - [x] Datum & Zeit: GDD date of registration

3. Count: Wie oft wurde die Aktion ausgeführt?
- [ ] #3139
- [ ] #3135
- [ ] #3136
- [ ] #3137
- [ ] #3138

4. URL der Home-Community z.B. https://gdd.gradido.net
- [ ] #3140

*Aktionen bei Aktivität*
- [ ] Datum & Zeit  setzen wenn 
  - [ ] 🚀 [Feature] KlickTipp Export: Transaktion gesendet wurde:  'GDD last sent'
  - [ ] 🚀 [Feature] KlickTipp Export: Transaktion empfangen wurde: 'GDD last received'
  - [ ] 🚀 [Feature] KlickTipp Export: Contribution eingereicht wurde: 'GDD last created'
  - [ ] 🚀 [Feature] KlickTipp Export: Neuer User erfolgreich per Link eingeladen

Anzahl, wie oft die betreffende Aktion ausgeführt wurde in das betreffende Feld setzen

Alle weitere Logik macht Bernd bei Klick-Tipp

previous conception and requirements
--------------------------------------
As community manager I would like that the Application sends a call to KlickTipp to set a tag on users:
> - seit x Tagen noch keinen Gemeinwohl-Beitrag eingereicht
> - seit x Tagen  noch keine Transaktion (Überweisung o.ä.) getätigt
> - Tags entziehen, wenn es nicht mehr zutrifft.
> Dann könnte man die inaktiven User einladen, aktiv zu werden.
>
> Man könnte auch übemitteln, wenn jemand (k)einen anderen User geworben hat,  etc.
>
> oder alternativ Felder bei Klick-Tipp befüllen:
> Anzahl und Gesamtbetrag der Schöpfungen in den letzten 30 Tagen
> Anzahl und Gesamtbetrag der ausgehenden Transaktionen in den letzten 30 Tagen
> Anzahl der geworbenen neuen User in den letzten 10, 30, 90 Tagen

> Die Fragen die sich stellen sind: 
> - wie beziehungsweisse wann werden die calls zum hinzufügen der tags angestoßen: 
>   - Über einen cron-job
>   - Über Benutzer interaction im admin interface? Wenn ja würde als folge Frage "wo soll die funktion in der UI hin?" entstehen.
>   - ??? Andere Lösungen ???
> - welche tags sollen angelegt werden
> - entfernen der tags müsste dann auch definieren welche tags entfernt werden sollen
