### ISSUE TITLE
🌟 [EPIC] Upgrade Frontend and Admin to vue 3

### ISSUE THREAD

**Issue by Elweyn** [gradido/gradido#3071]
## 🌟 EPIC

For the upgrade of the modules frontend and admin to vue 3, 
we need to install the package; to remove the old package;
fix layouts of every page to the possible new structure given through vue 3.

### Frontend:
- [ ] 🚀 [Feature] Frontend: Install vue 3 package
- [ ] 🚀 [Feature] Frontend: Refactor Header Component to vue 3
- [ ] 🚀 [Feature] Frontend: Refactor Menu Component to vue 3
- [ ] 🚀 [Feature] Frontend: Refactor Login Page to vue 3
- [ ] 🚀 [Feature] Frontend: Refactor Register Page to vue 3
- [ ] 🚀 [Feature] Frontend: Refactor Forgot Password Page to vue 3
- [ ] 🚀 [Feature] Frontend: Refactor Set Password Page to vue 3
- [ ] 🚀 [Feature] Frontend: Refactor Overview Page to vue 3
- [ ] 🚀 [Feature] Frontend: Refactor Transaction List Page to vue 3
- [ ] 🚀 [Feature] Frontend: Refactor Send Coin Page to vue 3
- [ ] 🚀 [Feature] Frontend: Refactor Creation Page to vue 3
- [ ] 🚀 [Feature] Frontend: Refactor Information Page to vue 3
- [ ] 🚀 [Feature] Frontend: Refactor Settings Page to vue 3

### Admin:
- [ ] 🚀 [Feature] Admin: Install vue 3 package
- [ ] 🚀 [Feature] Admin: Refactor Header Component to vue 3
- [ ] 🚀 [Feature] Admin: Refactor Overview Page to vue 3
- [ ] 🚀 [Feature] Admin: Refactor User Search Page to vue 3
- [ ] 🚀 [Feature] Admin: Refactor Creation Page to vue 3
- [ ] 🚀 [Feature] Admin: Refactor Automatic Creation Page to vue 3
- [ ] 🚀 [Feature] Admin: Refactor Instances Page to vue 3
- [ ] 🚀 [Feature] Admin: Refactor Statistics Page to vue 3
