### ISSUE TITLE
🌟 [EPIC] 1.1.0 User Profile

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#368]
#### Features 
- [x] (Main Feature) Profile Page & Settings #126 & #409 & (optional) #249 & (optional) #353
- [x] Properly use backend language storage #209

#### Bugs
- [x] Transaction List alignment #289 
- [x] Typo #403 
- [x] Style #402 
- [x] Show App Version #401 #354 
- [x] Pagination of transactions #310 

#### Refactor
- [x] Decide Frontendframework #210 
- [x] Errorhandling #242 #420 #411
- [ ] Global event definition #321
- [x] Thanks Page #306 
- [x] Coverage at 30% (double)

#### Feature
- [ ] (optional) Change EMail #249 

#### Refactoring
- [x] (most important) Coverage #177
- [x] Error Messages #15 related to #242 
- [ ] (optional) User Image Upload #421
- [x] Remove Conan #223 

#### Feature
- [ ] (optional) Nickname User Identification #137 #163 #150 #183

#### Bugs
- [x] Transaction list sorting #398 
- [x] Show Pending Transactions #302 
- [x] Wrong PubKey in Transaction List #412 

#### Refactoring
- [x] (most important) Coverage #177
- [x] Memo for Transactions required #391 
- [x] Error Messages #15 related to #242 

#### Bugs
- [x] Balance not equal to the new frontend #399 

### Deploy

- [x] Do tests
- [ ] Make release version 1.1.0
- [ ] Publish & deploy release

For the tests:
- There must be no Design problems
- Every button, link, hover & page must work.
- The user does never get any unexpected results or visual / undefined behaviour
- Something doesn't make sense or is not fully implemented, we do not show it to the user (e.g. User Avatar - not shown to other users = not shown to anyone, we hide the feature)
Please see https://github.com/gradido/gradido/issues/236 for some ideas

### (optional) Backend:
(Make proper tickets for this could be a good start)

- [ ] Setup Backend Server
   - [ ] Express
   - [ ] Apollo
- [ ] Define GraphQL Schema (Entities)
- [ ] Setup communication via GraphQL Frontend <--> Backend
- [ ] Move API calls from Frontend to Backend
- [ ] JWT Authentication & Session Handling via Backend #410 #213 #13
