### ISSUE TITLE
🌟 [EPIC] 1.0.0 New Vue Interface

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#40]
## 🌟 EPIC

Gradido is now live in the so called `Stage1`.
- [x] User data is ported
- [x] We have a stable deployment
- [x] Vue Interface had its first tests and is considered beta/usable
- [x] We go open source as far as we can
- [x] We do first tests for decentralization
