### ISSUE TITLE
🌟 [EPIC] 2.0.0 - IOTA

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#41]
## 🌟 EPIC

Have IOTA - also called `Stage2` - running on Staging

@einhornimmond @BerndHueckstaedt @ogerly 
Following the questions that popuped up for me:
- What is the purpose of the IOTA tangle? 
- What problem do we want to solve with the tangle?

The IOTA tangle should store the transactions like a ``GDD transfer register / GDD Kassenbuch``?

It should permit for each user to restore his own GDD account (with every transaction) on another server?

With this would we write every community on the same tangle?
- No, every Community gets there own topic

What is the definition of the data block that needs to be stored?
- that I used so far, but I must go step by step and some things need to be updated. It isn't final but a good orientation
  https://github.com/gradido/gradido_protocol/tree/master/proto/gradido 
  https://github.com/gradido/gradido/blob/master/docu/Concepts/Snippets/images/classes.png
  https://github.com/gradido/gradido/blob/master/docu/Concepts/Snippets/images/example_blockchain.png

How would another Community restore the ``old transaction list`` of the user?
- with the topic and user public key it can be requested from gradido node
- without gradido node every transaction from users old community must be requested from Chronicle and filtered by user public key

### Example 1:
Community Hamburg User: Hannes & Community Dresden User: Alex.
Hannes sendet an Alex per federation von Hamburg nach Dresden.
In Hamburg wird gescheckt ob alles OK ist (letzte IOTA message ID wird als referentID in der folge Transaktion gespeichert) und sendet an Dresden (Hamburg speichert die PendingTransaction).
In Dresden wird gescheckt ob der User existiert, und speichert die Transaktion, antwortet success an Hamburg.
In Hamburg wird die PendingTransaction in die Transaction Tabelle geschrieben.
In Hamburg wird auf den IOTA Tangle eine neue Nachricht geschrieben mit (senderPubKey, receiverPubKey, referentID,encrypt(transaction({transactionDetails}, ...)))
Idee Alex: 
Wenn Dresden success an Hamburg sendet hat die Transaction einen grünen Hacken.
Wenn die IOTA Tangle geschrieben ist bekommt die Transaction ein zweiten Hacken.

### Example 2:
User: Hannes wandert und besucht Alex in Community Dresden.
Hannes hat sein Privat Key und würde die Daten in Community Dresden importieren.
Alex sendet an Hannes beide sind jetzt in der Community Dresden.
Alex checkt seine letzte IOTA Message und übernimmt die ID als referentID.
Gleiche funktionalität wie bis jetzt.
Wenn success schreibt Alex auf IOTA Tangle (alexPubKey, hannesPubKey, referentID, encrypt(transaction)).

Hört sich das nach den erwünschten Funktion?

## 🤖 ToDos
- [x] https://github.com/gradido/gradido/issues/3034
- [x] #3109
- [x] #3110
- [ ] #3111
- [ ] 🚀 [Feature][DLT-Connector] Chronicle installieren
- [ ] 🚀 [Feature][DLT-Connector] Applikation zur Abfrage der Datenbank im Chronicle mit einfachem User-Interface zur Listendarstellung der Einträge
- [ ] 🚀 [Feature][DLT-Connector] Entwicklung von Validierungsfunktionen

**Comment by einhornimmond** [comment]
closed, as we now use Hiero/Hedera because of changes in IOTA. IOTA dropped fee-free transaction and topic messages all together, so it is now better to use Hiero/Hedera. It has a transaction fee, but at least it still support topic messages.
