### ISSUE TITLE
🔧 [Refactor] Implement Login Call createUser on Apollo 

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#835]
## 🔧 Refactor ticket

Implement Login Call createUser on Apollo 
## ToDos:
- [ ] Query user with email: if exists throw Error('user already exists')?
- [ ] Check Password validity? 
- [ ] Create an DbUser with the provided values in it
- [ ] Save DbUser, if error => Throw Error
- [ ] See if we need the Pubkey & Privkey
- [ ] Case yes: Implement it
- [ ] Case no: remove it
- [ ] Implement EmailOptIn logic
